### ISSUE TITLE
Conflicts with justinmk/vim-syntax-extra

### ISSUE THREAD

**Issue by andreyorst** [bfrg/vim-cpp-modern#4] opened 2018-07-20 05:14 UTC
Calling your plugin before [justinmk/vim-syntax-extra](https://github.com/justinmk/vim-syntax-extra) will overwrite some highlighting of the latter.
```vim
Plug 'bfrg/vim-cpp-modern'
Plug 'justinmk/vim-syntax-extra'
```
![image](https://user-images.githubusercontent.com/19470159/42984244-4ba18afa-8bf4-11e8-90d3-329fc29ffc1d.png)

```vim
Plug 'justinmk/vim-syntax-extra'
Plug 'bfrg/vim-cpp-modern'
```
![image](https://user-images.githubusercontent.com/19470159/42984200-0dd779f0-8bf4-11e8-85d6-406085e9a359.png)

The same issue was with [octol/vim-cpp-enhanced-highlight](https://github.com/octol/vim-cpp-enhanced-highlight)

**Comment by bfrg** [comment] 2018-07-24 19:50
Sorry for the late reply. Unfortunately, I can't reproduce the first case. 
Could you add the following lines to your `vimrc` file and tell me what vim prints when you put the cursor on the opening and closing parentheses and press `<F6>` and `<F7>`? (Use your own mappings.)
```vim
" Show the stack of syntax hilighting classes affecting whatever is under the
" cursor. First item in list is the outer region, followed by items contained in
" that one (taken from Steve Losh's vimrc)
function! s:SynStack()
    echo join(map(synstack(line('.'), col('.')), 'synIDattr(v:val, ''name'')'), ' > ')
endfunction

" Display the syntax highlighting group of the item under the cursor
function! s:HiGroup()
    echo 'hi<' . synIDattr(synID(line('.'),col('.'),1),'name') . '> trans<'
                \ . synIDattr(synID(line('.'),col('.'),0),'name') . '> lo<'
                \ . synIDattr(synIDtrans(synID(line('.'),col('.'),1)),'name') . '>'
endfunction

nnoremap <F6> :call <sid>SynStack()<CR>
nnoremap <F7> :call <sid>HiGroup()<CR>
```

Why do you need vim-syntax-extra? Apart from highlighting the operators, it doesn't add anything else to C/C++ syntax highlighting. If that's what you need, there's [Valloric/vim-operator-highlight](https://github.com/Valloric/vim-operator-highlight). I could also add a new option for highlighting operators. The exact same lines as in vim-syntax-extra are already in the [syntax/c.vim](https://github.com/bfrg/vim-cpp-modern/blob/master/after/syntax/c.vim#L274-L301) file. They are just commented out at the moment.

**Comment by andreyorst** [comment] 2018-07-30 15:48
![image](https://user-images.githubusercontent.com/19470159/43407998-e3054bde-9428-11e8-8e6f-4181b4295793.png) :

F6:
```
cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen
 > cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen > cCustomParen
```

F7:
```
hi<> trans<cCustomParen> lo<>
```

---

![image](https://user-images.githubusercontent.com/19470159/43408042-00611e4c-9429-11e8-8007-1914bc6e6a2f.png) :

F6:
```
cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen
 > cCustomParen > cParen > cCustomParen > cParen > cCustomParen > cParen > cDelimiter
```

F7:
```
hi<cDelimiter> trans<cDelimiter> lo<Delimiter>
```

**Comment by andreyorst** [comment] 2018-08-15 07:41
> Apart from highlighting the operators, it doesn't add anything else to C/C++ syntax highlighting. If that's what you need, there's Valloric/vim-operator-highlight.

Yes I want my operators to be highlighted, but unfortunately Valloric's plugin works like crap:
![image](https://user-images.githubusercontent.com/19470159/44136760-a5158bf4-a076-11e8-9fc3-c3d1d65c1bb6.png)
Not only the colors are insane, it somehow doesn't work as it should when it comes to highlighting itself. I'd stick with solution that works fine out of the box, like [vim-syntax-extra](https://github.com/justinmk/vim-syntax-extra)

**Comment by bfrg** [comment] 2018-08-16 13:59
On my system, it's the other way around. The following order **breaks** the highlighting of parentheses:
```vim
Plug 'justinmk/vim-syntax-extra'
Plug 'bfrg/vim-cpp-modern'
```
This makes sense because [vim-syntax-extra](https://github.com/justinmk/vim-syntax-extra/blob/master/after/syntax/c.vim#L268-L269) highlights parentheses as `Delimiter`. But since you're also using vim-cpp-modern's `c.vim` syntax file, it partially gets overridden. I will take a closer look at it the next days. 
In general, I don't recommend using both, even if you load the plugins the other way around: in the end, you're parsing two almost identical `c.vim` syntax files.
Nevertheles, if you really need vim-syntax-extra, disable the function highlighting provided by vim-cpp-modern. Just add the following to your `.vimrc`:
```vim
let g:cpp_no_function_highlight = 1
```
Vim will then use the function highlighting provided by vim-syntax-extra and everything else will work fine. I will think about adding an option to enable operator highlighting. Then you could get rid of vim-syntax-extra (unless you need the other syntax files it provides, too).

**Comment by andreyorst** [comment] 2018-08-16 14:10
Thanks.

I work mostly with C, not C++, however sometimes I do actually need to work with C++, and since it has some extra syntax facilities, compared to C, and my C is highlighted heavily, I'm loosing myself in C++ without modern highlighting. It's not good sign, but whatever, I'm orienting with color in first place, so without It I need to actually read code, instead of looking for color-coded blocks of code. And because plugins conflict in such way, I just not feel myself like at home. However, so far there were no other conflicts between this two plugins, so I think that this issue isn't top priority here.

**Comment by bfrg** [comment] 2018-08-16 17:58
One more note:

Even when you disable function highlighting with `let g:cpp_no_function_highlight = 1`, your `C++` functions will still be highlighted from vim-syntax-extra. The reason why it still works is because the default `cpp.vim` syntax file that is shipped with Vim (in `$VIMRUNTIME`) reads the default `c.vim` syntax file. Hence, all `c.vim` syntax files will be sourced when you open a `C++` files.

**Comment by bfrg** [comment] 2018-08-26 20:45
I updated the syntax match for highlighting of function names. The syntax stack from above sort of bothered me (all the `cParen > cCustomParen > ...`). Now, you don't even have to put `let g:cpp_no_function_highlight = 1` into your `vimrc` anymore.

**Closed as completed by bfrg** 2018-08-26 20:45 UTC
